In [1]:
import numpy as np

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(1,10,2,dtype=np.float64)

array([ 1.,  3.,  5.,  7.,  9.])

In [12]:
np.arange(1,10,0.5,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

# Examining ndarray

In [29]:
da=np.arange(1,10,2,dtype=np.float64)
print(da)
da.shape

[ 1.  3.  5.  7.  9.]


(5,)

In [14]:
da.size

5

In [15]:
da.ndim

1

In [25]:
da.dtype

dtype('int64')

In [18]:
type(da)

numpy.ndarray

In [30]:
da.itemsize

8

In [21]:
x=da.data
list(x)

[1, 3, 5, 7, 9]

In [22]:
da

array([1, 3, 5, 7, 9])

In [23]:
#Memory usage
da.itemsize*da.size

20

In [28]:
64/8

8.0

In [37]:
y=[x**2 for x in range(0,10)]
t=[x**2 for x in range(0,10)]
print(y)
print(t)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [36]:
[i+j for i,j in zip(y,t)]

[0, 2, 8, 18, 32, 50, 72, 98, 128, 162]

In [38]:
x=np.arange(0,10)
y=x**2
t=x**2
print(y)
print(t)

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [39]:
y+t

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [40]:
np.array([2,5,6,8])

array([2, 5, 6, 8])

In [43]:
da=np.array([[1,2],[5,2]])
print(da)

[[1 2]
 [5 2]]


In [47]:
da.shape


(2, 2)

In [46]:
da.ndim

2

In [49]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [51]:
np.linspace(1,4)

array([ 1.        ,  1.06122449,  1.12244898,  1.18367347,  1.24489796,
        1.30612245,  1.36734694,  1.42857143,  1.48979592,  1.55102041,
        1.6122449 ,  1.67346939,  1.73469388,  1.79591837,  1.85714286,
        1.91836735,  1.97959184,  2.04081633,  2.10204082,  2.16326531,
        2.2244898 ,  2.28571429,  2.34693878,  2.40816327,  2.46938776,
        2.53061224,  2.59183673,  2.65306122,  2.71428571,  2.7755102 ,
        2.83673469,  2.89795918,  2.95918367,  3.02040816,  3.08163265,
        3.14285714,  3.20408163,  3.26530612,  3.32653061,  3.3877551 ,
        3.44897959,  3.51020408,  3.57142857,  3.63265306,  3.69387755,
        3.75510204,  3.81632653,  3.87755102,  3.93877551,  4.        ])

In [52]:
np.linspace(1,4,num=8)

array([ 1.        ,  1.42857143,  1.85714286,  2.28571429,  2.71428571,
        3.14285714,  3.57142857,  4.        ])

In [55]:
np.linspace(1,4,num=8,endpoint=False)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625])

In [59]:
np.linspace(1,4,8)

array([ 1.        ,  1.42857143,  1.85714286,  2.28571429,  2.71428571,
        3.14285714,  3.57142857,  4.        ])

In [2]:
ra=np.random.random((3,4))
ra

array([[ 0.00968065,  0.74124302,  0.8434784 ,  0.3555076 ],
       [ 0.69702283,  0.43202917,  0.48272989,  0.25436209],
       [ 0.57740848,  0.51948206,  0.46869783,  0.08624734]])

# Statistics

In [63]:
np.max(ra)

0.97607024205199155

In [4]:
np.max(ra,axis=1)#column wise check

array([ 0.8434784 ,  0.69702283,  0.57740848])

In [67]:
np.min(ra)

0.24042716594431113

In [69]:
np.mean(ra,axis=0)

array([ 0.34861526,  0.81647867,  0.50133903,  0.66065139])

In [71]:
np.median(ra)

0.60684146998381816

In [72]:
np.std(ra)

0.2567391638567969

In [73]:
np.sum(ra)

6.9812530434479267

# Reshaping

In [76]:
np.reshape(ra,(2,6))

array([[ 0.42658073,  0.87099601,  0.76175759,  0.97607024,  0.24204729,
         0.7882231 ],
       [ 0.29033415,  0.24042717,  0.37721776,  0.79021688,  0.45192535,
         0.76545677]])

In [77]:
np.reshape(ra,12)

array([ 0.42658073,  0.87099601,  0.76175759,  0.97607024,  0.24204729,
        0.7882231 ,  0.29033415,  0.24042717,  0.37721776,  0.79021688,
        0.45192535,  0.76545677])

# Slicing

In [135]:
ra=np.random.random((5,10))
ra

array([[ 0.04746568,  0.06733902,  0.97119316,  0.99119688,  0.91043934,
         0.68305362,  0.17737563,  0.68142747,  0.14943182,  0.5094931 ],
       [ 0.91657413,  0.35232233,  0.91808098,  0.77994366,  0.34174446,
         0.18382047,  0.65830381,  0.7626624 ,  0.41100012,  0.65698538],
       [ 0.23274667,  0.70739142,  0.99775381,  0.31427646,  0.92536891,
         0.60333605,  0.0208988 ,  0.53869027,  0.52650098,  0.03673676],
       [ 0.06997765,  0.34300714,  0.46951992,  0.7982667 ,  0.23611749,
         0.87951156,  0.41052801,  0.66237146,  0.81251602,  0.51168038],
       [ 0.96651516,  0.64291609,  0.9409601 ,  0.02356564,  0.26757675,
         0.34035632,  0.41514169,  0.93610239,  0.12898301,  0.33284056]])

In [84]:
ra[0]

array([ 0.83308424,  0.67910283,  0.70083277,  0.52515228,  0.31495645,
        0.87277773,  0.83733347,  0.74034569,  0.02172958,  0.41263705])

In [85]:
ra[1][0]

0.97782113050865549

In [89]:
ra[1:4]

array([[ 0.97782113,  0.28841088,  0.28503803,  0.75557928,  0.38930723,
         0.80264305,  0.22984645,  0.01278938,  0.34594931,  0.20049132],
       [ 0.20283557,  0.8414059 ,  0.54625152,  0.23118621,  0.91868644,
         0.10178476,  0.36176262,  0.90223721,  0.12601859,  0.54117487],
       [ 0.60995427,  0.07933466,  0.67904476,  0.20193007,  0.99858099,
         0.53174357,  0.5044074 ,  0.46022901,  0.87841506,  0.94294978]])

In [91]:
ra[1:4,1]

array([ 0.28841088,  0.8414059 ,  0.07933466])

In [92]:
ra[1:4,0:2]

array([[ 0.97782113,  0.28841088],
       [ 0.20283557,  0.8414059 ],
       [ 0.60995427,  0.07933466]])

In [93]:
ra[:,1]

array([ 0.67910283,  0.28841088,  0.8414059 ,  0.07933466,  0.99033   ])

In [119]:
ra[2:4:2]

array([[ 0.20283557,  0.8414059 ,  0.54625152,  0.23118621,  0.91868644,
         0.10178476,  0.36176262,  0.90223721,  0.12601859,  0.54117487]])

In [106]:
ra[::]

array([[ 0.83308424,  0.67910283,  0.70083277,  0.52515228,  0.31495645,
         0.87277773,  0.83733347,  0.74034569,  0.02172958,  0.41263705],
       [ 0.97782113,  0.28841088,  0.28503803,  0.75557928,  0.38930723,
         0.80264305,  0.22984645,  0.01278938,  0.34594931,  0.20049132],
       [ 0.20283557,  0.8414059 ,  0.54625152,  0.23118621,  0.91868644,
         0.10178476,  0.36176262,  0.90223721,  0.12601859,  0.54117487],
       [ 0.60995427,  0.07933466,  0.67904476,  0.20193007,  0.99858099,
         0.53174357,  0.5044074 ,  0.46022901,  0.87841506,  0.94294978],
       [ 0.05620605,  0.99033   ,  0.3453156 ,  0.87222144,  0.4691714 ,
         0.27033067,  0.38131142,  0.68447436,  0.71536746,  0.02855849]])

In [116]:
ra[:,::2]

array([[ 0.83308424,  0.70083277,  0.31495645,  0.83733347,  0.02172958],
       [ 0.97782113,  0.28503803,  0.38930723,  0.22984645,  0.34594931],
       [ 0.20283557,  0.54625152,  0.91868644,  0.36176262,  0.12601859],
       [ 0.60995427,  0.67904476,  0.99858099,  0.5044074 ,  0.87841506],
       [ 0.05620605,  0.3453156 ,  0.4691714 ,  0.38131142,  0.71536746]])

In [111]:
ra[2:4]

array([[ 0.20283557,  0.8414059 ,  0.54625152,  0.23118621,  0.91868644,
         0.10178476,  0.36176262,  0.90223721,  0.12601859,  0.54117487],
       [ 0.60995427,  0.07933466,  0.67904476,  0.20193007,  0.99858099,
         0.53174357,  0.5044074 ,  0.46022901,  0.87841506,  0.94294978]])

In [113]:
ra[2:4,::2]

array([[ 0.20283557,  0.54625152,  0.91868644,  0.36176262,  0.12601859],
       [ 0.60995427,  0.67904476,  0.99858099,  0.5044074 ,  0.87841506]])

In [120]:
ra[1,1]=1

In [121]:
ra

array([[ 0.83308424,  0.67910283,  0.70083277,  0.52515228,  0.31495645,
         0.87277773,  0.83733347,  0.74034569,  0.02172958,  0.41263705],
       [ 0.97782113,  1.        ,  0.28503803,  0.75557928,  0.38930723,
         0.80264305,  0.22984645,  0.01278938,  0.34594931,  0.20049132],
       [ 0.20283557,  0.8414059 ,  0.54625152,  0.23118621,  0.91868644,
         0.10178476,  0.36176262,  0.90223721,  0.12601859,  0.54117487],
       [ 0.60995427,  0.07933466,  0.67904476,  0.20193007,  0.99858099,
         0.53174357,  0.5044074 ,  0.46022901,  0.87841506,  0.94294978],
       [ 0.05620605,  0.99033   ,  0.3453156 ,  0.87222144,  0.4691714 ,
         0.27033067,  0.38131142,  0.68447436,  0.71536746,  0.02855849]])

In [122]:
ra[1,:]=1

In [123]:
ra

array([[ 0.83308424,  0.67910283,  0.70083277,  0.52515228,  0.31495645,
         0.87277773,  0.83733347,  0.74034569,  0.02172958,  0.41263705],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.20283557,  0.8414059 ,  0.54625152,  0.23118621,  0.91868644,
         0.10178476,  0.36176262,  0.90223721,  0.12601859,  0.54117487],
       [ 0.60995427,  0.07933466,  0.67904476,  0.20193007,  0.99858099,
         0.53174357,  0.5044074 ,  0.46022901,  0.87841506,  0.94294978],
       [ 0.05620605,  0.99033   ,  0.3453156 ,  0.87222144,  0.4691714 ,
         0.27033067,  0.38131142,  0.68447436,  0.71536746,  0.02855849]])

In [124]:
ra[1,2:6]

array([ 1.,  1.,  1.,  1.])

In [125]:
ra[1,2:6]=[4,7,2,1]
ra

array([[ 0.83308424,  0.67910283,  0.70083277,  0.52515228,  0.31495645,
         0.87277773,  0.83733347,  0.74034569,  0.02172958,  0.41263705],
       [ 1.        ,  1.        ,  4.        ,  7.        ,  2.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.20283557,  0.8414059 ,  0.54625152,  0.23118621,  0.91868644,
         0.10178476,  0.36176262,  0.90223721,  0.12601859,  0.54117487],
       [ 0.60995427,  0.07933466,  0.67904476,  0.20193007,  0.99858099,
         0.53174357,  0.5044074 ,  0.46022901,  0.87841506,  0.94294978],
       [ 0.05620605,  0.99033   ,  0.3453156 ,  0.87222144,  0.4691714 ,
         0.27033067,  0.38131142,  0.68447436,  0.71536746,  0.02855849]])

In [129]:
t=[2.2,7,2,9]
ra[1,2:6]=t
ra

array([[ 0.83308424,  0.67910283,  0.70083277,  0.52515228,  0.31495645,
         0.87277773,  0.83733347,  0.74034569,  0.02172958,  0.41263705],
       [ 1.        ,  1.        ,  2.2       ,  7.        ,  2.        ,
         9.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.20283557,  0.8414059 ,  0.54625152,  0.23118621,  0.91868644,
         0.10178476,  0.36176262,  0.90223721,  0.12601859,  0.54117487],
       [ 0.60995427,  0.07933466,  0.67904476,  0.20193007,  0.99858099,
         0.53174357,  0.5044074 ,  0.46022901,  0.87841506,  0.94294978],
       [ 0.05620605,  0.99033   ,  0.3453156 ,  0.87222144,  0.4691714 ,
         0.27033067,  0.38131142,  0.68447436,  0.71536746,  0.02855849]])

In [136]:
inx=[2,3,4]
ra[1,inx]=-1
ra

array([[ 0.04746568,  0.06733902,  0.97119316,  0.99119688,  0.91043934,
         0.68305362,  0.17737563,  0.68142747,  0.14943182,  0.5094931 ],
       [ 0.91657413,  0.35232233, -1.        , -1.        , -1.        ,
         0.18382047,  0.65830381,  0.7626624 ,  0.41100012,  0.65698538],
       [ 0.23274667,  0.70739142,  0.99775381,  0.31427646,  0.92536891,
         0.60333605,  0.0208988 ,  0.53869027,  0.52650098,  0.03673676],
       [ 0.06997765,  0.34300714,  0.46951992,  0.7982667 ,  0.23611749,
         0.87951156,  0.41052801,  0.66237146,  0.81251602,  0.51168038],
       [ 0.96651516,  0.64291609,  0.9409601 ,  0.02356564,  0.26757675,
         0.34035632,  0.41514169,  0.93610239,  0.12898301,  0.33284056]])

In [145]:
inx=np.where(ra<=0 )
inx
ra[1,inx]=-1
print(ra)

[[ 0.04746568  0.06733902  0.97119316  0.99119688  0.91043934  0.68305362
   0.17737563  0.68142747  0.14943182  0.5094931 ]
 [ 0.91657413 -1.         -1.         -1.         -1.          0.18382047
   0.65830381  0.7626624   0.41100012  0.65698538]
 [ 0.23274667  0.70739142  0.99775381  0.31427646  0.92536891  0.60333605
   0.0208988   0.53869027  0.52650098  0.03673676]
 [ 0.06997765  0.34300714  0.46951992  0.7982667   0.23611749  0.87951156
   0.41052801  0.66237146  0.81251602  0.51168038]
 [ 0.96651516  0.64291609  0.9409601   0.02356564  0.26757675  0.34035632
   0.41514169  0.93610239  0.12898301  0.33284056]]


In [5]:
x=np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
t=[1,1,1,1]
x[1:5]=t

In [7]:
x

array([1, 1, 1, 1, 1, 6, 7, 8])

In [8]:
x[0:6]

array([1, 1, 1, 1, 1, 6])

In [7]:
x=[[3,6,7,1],[2,4,6,7,8,2,3]]

In [2]:
x

[[3, 6, 7, 1], [2, 4, 6, 7, 8, 2, 3]]

In [8]:
x[0][:]

[3, 6, 7, 1]

In [9]:
for i in range(0,len(x)):
    print(x[i][:])
    

[3, 6, 7, 1]
[2, 4, 6, 7, 8, 2, 3]


In [3]:
np.r_[np.array([1,2,3]), 0, 0, np.array([4,5,6])]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [6]:
np.r_[-1:1:6j]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [2]:
np.r_[-1:1:6j, [0]*3, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  0. ,  5. ,  6. ])